# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - strapionazuredemo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://hub.docker.com//
        username: ${{ secrets.AzureAppService_ContainerUsername_a72e69c2df5c439da8ae0ee4fd15144e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d3285dbb7e404266a248b50832f5aade }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hub.docker.com//${{ secrets.AzureAppService_ContainerUsername_a72e69c2df5c439da8ae0ee4fd15144e }}/strapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'strapionazuredemo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b081ca3358b640b7b0ef1426c59c5dd5 }}
        images: 'hub.docker.com//${{ secrets.AzureAppService_ContainerUsername_a72e69c2df5c439da8ae0ee4fd15144e }}/strapi:${{ github.sha }}'