# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - strapionazuredemo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_8a12c77d7a114c02a02281013d53267a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ae4a8c5d27754eda96fe9ad7115f8568 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8a12c77d7a114c02a02281013d53267a }}/mydocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'strapionazuredemo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_da766cb9f1364c4b873772f9ab8fff48 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_8a12c77d7a114c02a02281013d53267a }}/mydocker:${{ github.sha }}'